<?php

namespace Oro\IssueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends EntityRepository
{
    public function findByCollaborator($userId)
    {
        $queryBuilder = $this->createQueryBuilder('i')
            ->select('i')
            ->addOrderBy('i.createdAt', 'DESC')
            ->join('i.collaborators', 'u')
            ->where('u.id = :user_id')
            ->setParameter('user_id', $userId);

        return $queryBuilder->getQuery()->getResult();
    }
}
