parameters:
#    oro_project.example.class: Oro\ProjectBundle\Example

services:
    oro.security.project_voter:
        class:      Oro\ProjectBundle\Security\ProjectVoter
        public:     false
        tags:
            - { name: security.voter }