parameters:
#    oro_project.example.class: Oro\ProjectBundle\Example

services:
#    oro_project.example:
#        class: %oro_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
