parameters:
    oro_project.security.project_voter.class: Oro\ProjectBundle\Security\ProjectVoter
    oro_project.form.project.type.class: Oro\ProjectBundle\Form\ProjectType

services:
    oro_project.security.project_voter:
        class:      "%oro_project.security.project_voter.class%"
        public:     false
        tags:
            - { name: security.voter }

    oro_project.form.project.type:
        class: "%oro_project.form.project.type.class%"
        tags:
            - {name: form.type, alias: oro_projectbundle_project}
