oro_issue:
    resource: "@OroIssueBundle/Resources/config/routing.yml"
    prefix:   /issue

oro_project:
    resource: "@OroProjectBundle/Resources/config/routing.yml"
    prefix:   /project

oro_user:
    resource: "@OroUserBundle/Resources/config/routing.yml"
    prefix:   /

