parameters:
    oro_issue.event_listener.comment_listener.class: Oro\IssueBundle\EventListener\CommentListener
    oro_issue.event_listener.activity_listener.class: Oro\IssueBundle\EventListener\ActivityListener
    oro_issue.event_listener.issue_listener.class: Oro\IssueBundle\EventListener\IssueListener
    oro_issue.security.issue_voter: Oro\IssueBundle\Security\IssueVoter
    oro_issue.security.comment_voter: Oro\IssueBundle\Security\CommentVoter
    oro_issue.form.issue.type.class: Oro\IssueBundle\Form\IssueType
    oro_issue.form.comment.type.class: Oro\IssueBundle\Form\CommentType

services:
    comment.listener:
        class: "%oro_issue.event_listener.comment_listener.class%"
        tags:
            - {name: doctrine.event_listener, event: postPersist}

    activity.listener:
        class: "%oro_issue.event_listener.activity_listener.class%"
        arguments: [@service_container]
        tags:
            - {name: doctrine.event_listener, event: postPersist}

    issue.listener:
        class: "%oro_issue.event_listener.issue_listener.class%"
        arguments:
            - @oro.user.user_callable
        tags:
            - {name: doctrine.event_listener, event: preUpdate}
            - {name: doctrine.event_listener, event: postFlush}
            - {name: doctrine.event_listener, event: postPersist}
            - {name: doctrine.event_listener, event: onFlush}

    oro.security.issue_voter:
        class:      "%oro_issue.security.issue_voter%"
        public:     false
        tags:
            - { name: security.voter }

    oro.security.comment_voter:
        class:      "%oro_issue.security.comment_voter%"
        public:     false
        tags:
            - { name: security.voter }

    oro_issue.form.issue.type:
        class: "%oro_issue.form.issue.type.class%"
        tags:
            - {name: form.type, alias: oro_issuebundle_issue}

    oro_issue.form.comment.type:
        class: "%oro_issue.form.comment.type.class%"
        tags:
            - {name: form.type, alias: oro_issuebundle_comment}
