Oro\IssueBundle\Entity\Issue:
    constraints:
        - Callback:
            methods: [validateParent]
    properties:
        summary:
            - NotBlank: ~
        createdAt:
            - DateTime: ~
        updatedAt:
            - DateTime: ~

Oro\IssueBundle\Entity\Comment:
    properties:
        body:
            - NotBlank: ~
        createdAt:
            - DateTime: ~
        updatedAt:
            - DateTime: ~
