parameters:
    oro.timezone: Europe/Kiev
    oro.user.user_callable.class: Oro\UserBundle\DependencyInjection\UserCallable

services:
    oro.user.user_callable:
        class: "%oro.user.user_callable.class%"
        arguments:
            - @service_container

    oro.security.user_voter:
        class:      Oro\UserBundle\Security\UserVoter
        public:     false
        tags:
            - { name: security.voter }