parameters:
#    oro_user.example.class: Oro\UserBundle\Example

services:
#    oro_user.example:
#        class: %oro_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
