parameters:
    oro.user.user_callable.class: Oro\UserBundle\DependencyInjection\UserCallable

services:
    oro.user.user_callable:
        class: "%oro.user.user_callable.class%"
        arguments:
            - "@service_container"
